### ISSUE TITLE
LIA-142 Bugs from test results

### ISSUE THREAD

**Issue by eldardo** [lianetoolkit/liane-toolkit#142]
- the import process works correctly
- the modal to match between fields also works ok.
- When you finish importing some duplicates appear and others do not. I don't understand the logical reasons
- With the duplicates that the merge process found, it works well, but it was not so usable to solve a person who did not want to mix or eliminate. The merge worked.
- The tags are wrong, it is like it takes person id instead of tags, maybe they are people id, so they should not be called tags
- When the process ends, it continues showing the initial number of cases found when importing the base, but the board is empty.

**Comment by miguelpeixe** [comment]
- identify just one parent (the first identified - oldest) for the `unresolved` group

**Comment by eldardo** [comment]
- Potential duplicates ignored by the system
<img width="758" alt="test_nolotoma" src="https://user-images.githubusercontent.com/5084966/89233027-1c63e500-d5bf-11ea-9c6a-68f44a41b175.PNG">


- Another potential duplicates ignored by the system
<img width="744" alt="test_soledad_castro" src="https://user-images.githubusercontent.com/5084966/89233032-1ec63f00-d5bf-11ea-8491-2ba5235951ba.PNG">


- Tags or ID?
<img width="597" alt="test_tags_extraños" src="https://user-images.githubusercontent.com/5084966/89233029-1d951200-d5bf-11ea-8f44-0d029d3bb637.PNG">

- after solving the number does not change, nor does it button disappear.
<img width="751" alt="test_lead_duplicates" src="https://user-images.githubusercontent.com/5084966/89233031-1ec63f00-d5bf-11ea-9dbe-4aaf9e860c82.PNG">

**Comment by nefertiter** [comment]
@eldardo 
- Tags and birthdays show have been fixed.
- The last issue described as well should have been fixed as well. 

Please perform one more test, and provide any xls file if needed to reproduce.

**Comment by eldardo** [comment]
@nefertiter 

-   test performed with this file 
[teste_merge.xlsx](https://github.com/lianetoolkit/liane-toolkit/files/5038564/teste_merge.xlsx)

- and this is the result (looks good!)
<img width="940" alt="test0608_01" src="https://user-images.githubusercontent.com/5084966/89593612-f7bd7680-d825-11ea-95b5-c0da23a58f68.PNG">

- but... tags still don't work properly
<img width="599" alt="test0608_02" src="https://user-images.githubusercontent.com/5084966/89593660-1ae82600-d826-11ea-932d-b9e26ae090d6.PNG">

- and cases of the same name with upper and lower case are not recognized
<img width="750" alt="test0608_05" src="https://user-images.githubusercontent.com/5084966/89593704-3a7f4e80-d826-11ea-9399-c4259fe1cca6.PNG">
 
- all other functions seems to be ok!

**Comment by miguelpeixe** [comment]
Weird about the tags, on test.liane I got the tag name properly:

![image](https://user-images.githubusercontent.com/820752/89595805-e0818780-d82b-11ea-8d15-eec6130a8351.png)

**Comment by eldardo** [comment]
@miguelpeixe Can you test by putting a number on the label? I find that difference between the two examples.

**Comment by miguelpeixe** [comment]
Ah, it's on the next screen. Both with number of just letters I got the ID being displayed at the confirmation table:

![image](https://user-images.githubusercontent.com/820752/89646668-91bb0880-d892-11ea-95d9-45e730611a3b.png)

**Comment by eldardo** [comment]
Hi @miguelpeixe and @nefertiter ¡the new test was almost perfect, almost everything worked, only that....

 "ana laura de giorgi" found 106 duplicates!!!!

because it took all the "ana" and all the "laura" from the database, plus a lot of "ana laura" . I think we need to improve that intelligence, that the maximum difference can be 3 letters, or something like that. 

<img width="788" alt="anamaslaura" src="https://user-images.githubusercontent.com/5084966/90193752-fd720980-dd9b-11ea-953d-9bb443c5db2f.PNG">

and, i dont understan why why doesn't the same thing happen with all the "juan pedro" for example...

<img width="749" alt="juan no pedro" src="https://user-images.githubusercontent.com/5084966/90193900-4fb32a80-dd9c-11ea-8790-ec118771a3e7.PNG">

**Comment by nefertiter** [comment]
@eldardo it shows whats similar but for sure its sjusts too much, we have set the "score" to be a mininum of "1", and we have seen when the perfect match its 2.5, we should raise the 1 to a higher, maybe 1.2 ? @miguelpeixe

**Comment by miguelpeixe** [comment]
Wow! Yes, let's raise it to 1.2 and give it another try.

**Comment by miguelpeixe** [comment]
After some research I realized that the score will always be small if the string has few characters, even if its an exact match. I made some changes to accomplish 2 goals: case-insensitive exact matches and small differences for strings with higher amount of characters.

I'm assuming differences in names with few characters has a very high risk of being a completely different name.

For that I increased the $search query score to **higher than 1.5** and also included a **RegExp query for case-insensitive exact maching**. The new RegExp query should handle cases like Ana - ana - ANA, which is exact but too few characters for score matching.

cc @eldardo @nefertiter
